<!DOCTYPE html>
<html lang="en">

    <head>
    <meta charset="utf-8" />
        <title>Olik - Privacy Policy</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Olik Privacy Policy" />
        <meta name="keywords" content="Privacy Policy" />
        <meta name="author" content="Olik Inc" />
        <meta name="email" content="mohit@olik.ai" />
        <meta name="website" content="https://olik.ai" />
        <meta name="Version" content="v2.0.0" />
        <!-- favicon -->
        <link href="images/favicon.png" rel="shortcut icon">
        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- Icons -->
        <link href="css/materialdesignicons.min.css" rel="stylesheet" type="text/css" />
        <link href="https://unicons.iconscout.com/release/v3.0.6/css/line.css" rel="stylesheet" />
        <!-- Main Css -->
        <link href="css/style.min.css" rel="stylesheet" type="text/css" id="theme-opt" />
        <?php include "head-scripts.php" ?>
    </head>

    <body>        
        <!-- Navbar STart -->
                <!-- Navbar STart -->
                <?php include "head-navigation.php" ?>
        <!-- Navbar End -->
        <!-- Hero Start -->
        <section class="bg-half-170 d-table w-100" style="background: url('images/bg/blog01.jpg') center;">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold page-heading text-white title-dark">Privacy Policy</h5>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->
            </div><!--end container-->
        </section><!--end section-->
        <!-- Hero End -->

        <!-- Start -->
        <section class="section">
            <div class="container">
            <div class="row">
                    <p>This policy explains how Olik, a brand of Olik Inc, uses your personal
information which you provide to us when using our service, via our website and mobile
application.</p>

<p><strong>What user information do we collect?</strong><br>
We collect personal information from you when you order goods or services from us or use
our website or app. We also collect information when you complete any customer survey.
Website usage information may also be collected using cookies.</p>

<p><strong>Cookies and Google Analytics</strong><br>
Cookies are small text files that are placed on your computer/mobile by websites that you
visit. They are widely used in order to make websites/apps work, or work more efficiently,
as well as to provide information to the owners of the site.
This website uses Google Analytics, a web analytics service provided by Google, Inc.
("Google"). Google Analytics uses "cookies", which are text files saved on your computer, to
help the website analyze how you use the site. The information generated by the cookie
about your use of the website will be transmitted to and stored by Google on servers in the
United States. If this website anonymizes IP addresses, your IP address will be truncated by
Google within a EU member state or other EEA state before being transmitted to the US.
Only in exceptional situations will your full IP address be transmitted to Google servers in
the United States and truncated there. Google will use this information for the purpose of
evaluating your use of the website, compiling reports on website activity for website
operators and providing other services relating to website activity and internet usage.
Google will not associate your IP address with any other data held by Google. You may
refuse the use of cookies by selecting the appropriate settings on your browser, however
please note that if you do this you may not be able to use the full functionality of this
website. By using this website, you consent to the processing of data about you by Google in
the manner and for the purposes set out above. You can also prevent Google from collecting
information (including your IP address) via cookies and processing this information by
downloading this browser plugin and installing it:https://tools.google.com/dlpage/gaoptout
Most web browsers allow some control of most cookies through the browser settings. To
find out more about cookies, including how to see what cookies have been set and how to
manage and delete them, visit www.allaboutcookies.org.</p>

<p><strong>How will we use the information we collect from you?</strong><br>
Information that we collect from you is used to process your order and to manage your
account.</p>

<p><strong>Access to your information</strong><br>
You have a right to request a copy of the information we hold on you at any time. Please
email us if you would like to receive a copy of this information - support@olik.ai</p>

<p><strong>Other Websites</strong><br>
Our website may have links to other websites. This privacy policy only applies to this
website. You should therefore read the privacy policies of the other websites when you are
using those sites.</p>

<p>By using or accessing this Website, you agree to the terms and conditions of this Privacy
Policy. You also expressly consent to our use and disclosure of your Personal Information (as
possessed by us) in any manner as described in this Privacy Policy and further signify your
agreement to this Privacy Policy and the Terms of Use (being incorporated by reference
herein).</p>
                </div><!--end row-->
            </div><!--end container-->
        </section><!--end section-->
        <!-- End -->

        <?php include "footer.php" ?>

        <!-- Back to top -->
<a href="javascript:void(0)" onclick="topFunction()" id="back-to-top" class="back-to-top rounded-pill"><i class="mdi mdi-arrow-up"></i></a>
        <!-- Back to top -->
    

        <!-- javascript -->
        <script src="js/bootstrap.bundle.min.js"></script>
        <!-- Icons -->
        <script src="js/feather.min.js"></script>
        <!-- Main Js -->
        <script src="js/plugins.init.js"></script><!--Note: All init js like tiny slider, counter, countdown, maintenance, lightbox, gallery, swiper slider, aos animation etc.-->
        <script src="js/app.js"></script><!--Note: All important javascript like page loader, menu, sticky menu, menu-toggler, one page menu etc. -->
    </body>
</html>